@file:Suppress("LombokKotlinCompilerPlugin")

package com.mistbeyond.transport.data.model

import com.mojang.math.Quadrant
import com.mistbeyond.transport.Ids
import com.mistbeyond.transport.block.Blocks
import com.mistbeyond.transport.block.rail.RailTrackCellBlock
import com.mistbeyond.transport.api.rail.graph.TrackAxis
import com.mistbeyond.transport.item.Items
import net.minecraft.client.data.models.BlockModelGenerators
import net.minecraft.client.data.models.ItemModelGenerators
import net.minecraft.client.data.models.ModelProvider
import net.minecraft.client.data.models.blockstates.MultiVariantGenerator
import net.minecraft.client.data.models.blockstates.PropertyDispatch
import net.minecraft.client.data.models.model.ModelTemplates
import net.minecraft.core.Holder
import net.minecraft.data.PackOutput
import net.minecraft.resources.Identifier
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block
import java.util.stream.Stream

class ModModelProvider(output: PackOutput) : ModelProvider(output, Ids.MOD_ID) {
    override fun registerModels(blockModels: BlockModelGenerators, itemModels: ItemModelGenerators) {
        val testTrack = Blocks.BLOCKS.entries.stream()
            .filter { it.id.path == "rail_track_cell" }
            .findFirst()
            .orElseThrow()
            .value()
        val trackModel = Identifier.fromNamespaceAndPath(Ids.MOD_ID, "block/track")
        val diagonalModel = Identifier.fromNamespaceAndPath(Ids.MOD_ID, "block/track_diagonal")
        // The simple-cell BlockState stores one of the four track axes. block/track has its rails along the Z axis
        // (north-south), so N_S stays unrotated and E_W rotates 90 degrees, mirroring the vanilla rail blockstate.
        // The diagonal model (track_diagonal, generated by TrackModelGenerator) is built from a Z-axis strip rotated
        // +45 degrees around Y (counter-clockwise seen from above, JOML right-handed convention), so its rails run
        // NW-SE at y=0; NE_SW gets the 90-degree rotation to flip the rails onto the NE-SW axis.
        val axisRotation = mapOf(
            TrackAxis.N_S to Quadrant.R0,
            TrackAxis.E_W to Quadrant.R90,
            TrackAxis.NE_SW to Quadrant.R90,
            TrackAxis.NW_SE to Quadrant.R0
        )
        blockModels.blockStateOutput.accept(
            MultiVariantGenerator.dispatch(testTrack).with(
                PropertyDispatch.initial(RailTrackCellBlock.DIRECTION).generate { axis ->
                    val model = if (axis.diagonal()) diagonalModel else trackModel
                    val variant = BlockModelGenerators.plainModel(model).withYRot(
                        axisRotation[axis] ?: Quadrant.R0
                    )
                    BlockModelGenerators.variant(variant)
                }
            )
        )
        blockModels.registerSimpleItemModel(testTrack, trackModel)
        // The diagonal 45 straight model is generated programmatically from the same parametric
        // geometry; the hand-written Blockbench export it replaces was not symmetric.
        TrackModelGenerator.generateDiagonal(blockModels)

        val trainSpawner = Items.ITEMS.entries.stream()
            .filter { it.id.path == "test_train_spawner" }
            .findFirst()
            .orElseThrow()
            .value()
        itemModels.generateFlatItem(trainSpawner, net.minecraft.world.item.Items.MINECART, ModelTemplates.FLAT_ITEM)
    }

    override fun getKnownBlocks(): Stream<out Holder<Block>> = Blocks.BLOCKS.entries.stream()

    override fun getKnownItems(): Stream<out Holder<Item>> = Items.ITEMS.entries.stream()
}
